# Generated by Django 4.2.9 on 2024-06-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.FloatField(help_text='Total bandwidth limit in MB')),
                ('used', models.FloatField(help_text='Total bandwidth used in MB')),
                ('free', models.FloatField(help_text='Total bandwidth free in MB')),
                ('limit_gb', models.FloatField(help_text='Total bandwidth limit in GB')),
                ('used_gb', models.FloatField(help_text='Total bandwidth used in GB')),
                ('free_gb', models.FloatField(help_text='Total bandwidth free in GB')),
                ('percent', models.FloatField(help_text='Percentage of bandwidth used')),
                ('percent_free', models.FloatField(help_text='Percentage of bandwidth free')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='Hostname of the server', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the server')),
                ('api_key', models.CharField(max_length=255)),
                ('api_password', models.CharField(max_length=255)),
                ('panel_ipaddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of usage')),
                ('in_usage', models.FloatField(help_text='Inbound usage in MB')),
                ('out_usage', models.FloatField(help_text='Outbound usage in MB')),
                ('bandwidth_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to='bandwidth.bandwidthusage')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to='bandwidth.server')),
            ],
        ),
        migrations.AddField(
            model_name='bandwidthusage',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_usages', to='bandwidth.server'),
        ),
        migrations.CreateModel(
            name='BandwidthOutUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.JSONField(help_text='JSON field storing daily out-bandwidth usage')),
                ('used', models.FloatField(help_text='Total out-bandwidth used in MB')),
                ('limit', models.FloatField(help_text='Total out-bandwidth limit in MB')),
                ('free', models.FloatField(help_text='Total out-bandwidth free in MB')),
                ('limit_gb', models.FloatField(help_text='Total out-bandwidth limit in GB')),
                ('used_gb', models.FloatField(help_text='Total out-bandwidth used in GB')),
                ('free_gb', models.FloatField(help_text='Total out-bandwidth free in GB')),
                ('percent', models.FloatField(help_text='Percentage of out-bandwidth used')),
                ('percent_free', models.FloatField(help_text='Percentage of out-bandwidth free')),
                ('bandwidth_usage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='out_bandwidth', to='bandwidth.bandwidthusage')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_bandwidth_usages', to='bandwidth.server')),
            ],
        ),
        migrations.CreateModel(
            name='BandwidthInUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.JSONField(help_text='JSON field storing daily in-bandwidth usage')),
                ('used', models.FloatField(help_text='Total in-bandwidth used in MB')),
                ('limit', models.FloatField(help_text='Total in-bandwidth limit in MB')),
                ('free', models.FloatField(help_text='Total in-bandwidth free in MB')),
                ('limit_gb', models.FloatField(help_text='Total in-bandwidth limit in GB')),
                ('used_gb', models.FloatField(help_text='Total in-bandwidth used in GB')),
                ('free_gb', models.FloatField(help_text='Total in-bandwidth free in GB')),
                ('percent', models.FloatField(help_text='Percentage of in-bandwidth used')),
                ('percent_free', models.FloatField(help_text='Percentage of in-bandwidth free')),
                ('bandwidth_usage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='in_bandwidth', to='bandwidth.bandwidthusage')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_bandwidth_usages', to='bandwidth.server')),
            ],
        ),
    ]
