# Generated by Django 5.0.1 on 2024-01-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='domaininfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=100)),
                ('servername', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
            ],
        ),
    ]
