# Generated by Django 4.2.9 on 2024-05-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_alter_domaininfo_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='ipaddress',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='specificid',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='zoneid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
