# Generated by Django 4.2.9 on 2024-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainconvert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertdomain',
            name='rootdomain',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
